const ClientErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PRODUCT_UNAVAILABLE_ERROR: 'PRD_UNAVL_001',
  PRODUCT_MAX_QUANTITY_EXCEEDED_ERROR: 'PRD_UNAVL_001',
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  BAD_REQUEST: 'BAD_REQUEST',
  CONFLICT: 'CONFLICT',
  FETCH_FAILED: 'FETCH_FAILED',
  BUSINESS_ERROR: 'BUS_ERR_001',
  INVALID_OTP: 'INV_OTP_001',
  REFRESH_TOKEN_NOT_FOUND: 'REF_TK_NF_001',
  TOKEN_EXPIRED: 'TK_EXP_001',
  INVALID_REFRESH_TOKEN: 'INV_REF_TK_001',
  INVALID_CREDENTIALS: 'INV_CRED_001',
  ORDER_INCONSISTENT_STATE_ERROR: 'ORD_INCST_001',
  DELIVERY_NOT_OFFERED_ERROR: 'DLV_NO_001',
};

const InternalErrorCodes = {
  // Database related
  DB_CONNECTION: 'DB_001',
  DB_QUERY: 'DB_002',
  DB_TRANSACTION: 'DB_003',

  // Service related
  SERVICE_ERROR: 'SVC_001',
  EXTERNAL_API: 'SVC_002',

  // System related
  SYSTEM_ERROR: 'SYS_001',
  FILE_SYSTEM: 'SYS_002',
};

const ErrorCodes = { ClientErrorCodes, InternalErrorCodes };

module.exports = { ErrorCodes };
